### ISSUE TITLE
references to data now all incorrect?

### ISSUE THREAD

**Issue by JanOdijk** [UUDigitalHumanitieslab/sastadev#17]
Ik zie nu dat de verwijzing naar de methods folder nu fout is, want die staat nu in de data folder. Heb jij dat aangepast en is dit een oversight of moet nog in alle verwijzingen naar ‘data’ de datafolder toegevoegd worden?

ik wil dat wel doen waar nodig (wil toch alles testen), dan maak ik daarvoor een nieuwe branch aan.
Jan

**Comment by JeltevanBoheemen** [comment]
Ik dacht dat ik alle paden had bijgewerkt. Maar mogelijk heb ik er 1 gemist. Waar in de code gaat het mis?

**Comment by JeltevanBoheemen** [comment]
Resolved in  9bdc4c5
