### ISSUE TITLE
Sastadev; er zijn nu twee packages

### ISSUE THREAD

**Issue by JanOdijk** [UUDigitalHumanitieslab/sastadev#19]
Ik roep nu sastadev aan vanuit een ander programma.

python "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\__main__.py" -f "D:\Dropbox\jodijk\Utrecht\Projects\SASTADATA\vkltarsp\intreebanks\Tarsp_01.xml" -m "tarsp"  --corr 0  
Traceback (most recent call last):
  File "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\__main__.py", line 150, in <module>
    from sastadev import compounds
ImportError: cannot import name 'compounds' from 'sastadev' (C:\Users\Odijk101\Anaconda3\envs\auchantest\lib\site-packages\sastadev\__init__.py)

Ik denk dat ie nu de sastadev package van Sheean neemt (die bij AuChann meegeleverd wordt) en daar vindt ie natuurlijk geen compounds module. Hoe vermijd ik dit?

**Comment by JeltevanBoheemen** [comment]
Ik vermoed dat het probleem is dat je rechtstreeks `sastadev.__main__` aanroept:
```
python "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev_main_.py" <args>
```
Als je het als module draait zou het moeten werken:
```
python -m "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev" <args>
```
Nog beter: in het programma dat je draait (als je daar een virtual environment voor hebt):
```
pip install -e D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev
sastadev <args>
```

**Comment by JeltevanBoheemen** [comment]
Als er inderdaad nog een pypi versie van sastadev geinstalleerd is, eerst:

```
pip uninstall sastadev
```

**Comment by JanOdijk** [comment]
OK, na jouw laatste aanwijzingen doet ie het nu op de command line. (ik heb wat versie info statements toegevoegd aan sastadev)
(base) D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src>python -m sastadev
Configuration initiated.
Python              : sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
lxml.etree          : (4, 5, 2, 0)
libxml used         : (2, 9, 5)
libxml compiled     : (2, 9, 5)
libxslt used        : (1, 1, 30)
libxslt compiled    : (1, 1, 30)



maar niet vanuit pycharm:, daar klaagt ie weer over 'unknown error', veroorzaakt door lange XPATH queries:

C:\Users\Odijk101\Anaconda3\envs\sastadev\python.exe D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\__main__.py -f D:\Dropbox\jodijk\Utrecht\Projects\SASTADATA\vkltarsp\intreebanks\tarsp_01.xml -m tarsp 
Configuration initiated.
Python              : sys.version_info(major=3, minor=7, micro=13, releaselevel='final', serial=0)
lxml.etree          : (4, 5, 2, 0)
libxml used         : (2, 9, 14)
libxml compiled     : (2, 9, 10)
libxslt used        : (1, 1, 35)
libxslt compiled    : (1, 1, 34)

Process finished with exit code 0

Volgens Nick Hoffnweller moet ik libxml 2.9.13 of hoger gebruiken. Jij hebt wel eens uitgelegd wat ik daarvoor moiet doen, maar daar heb ik toch echt je hulp bij nodig.

Jan
