### ISSUE TITLE
Missing dependency when installing from package?

### ISSUE THREAD

**Issue by bbonf** [UUDigitalHumanitieslab/sastadev#22]
See https://github.com/UUDigitalHumanitieslab/mwe-query/actions/runs/5879266792/job/15942950883#step:6:24 about missing `typing_extensions`, although I do see it in sastadev's requirements.txt via mypy.

Any idea what went wrong here?

**Comment by JeltevanBoheemen** [comment]
The `requirements.txt` of `sastadev` aren't installed when installing the package through `pip`. I'll have to add them to `install_requires` in `setup.py`. Good find.

**Comment by JeltevanBoheemen** [comment]
Should be resolved in [be712d8](https://github.com/UUDigitalHumanitieslab/sastadev/commit/be712d89847b198dfe0ad7dae03e8937f8ecf271)
